services:
  - type: web
    name: bichodata-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SPREADSHEET_ID
        sync: false
      - key: SHEET_NAME
        value: RESULTADOS
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
